TEMPLATE = app
CONFIG += console c++11
CONFIG -= app_bundle
CONFIG -= qt

SOURCES += \
        libs/QRCodeGen/qrcodegen.cpp \
        libs/TinyPNGOut/TinyPngOut.cpp \
        main.cpp \
        qrcode.cpp \
        vcard.cpp

HEADERS += \
    libs/QRCodeGen/qrcodegen.hpp \
    libs/SFML/include/SFML/Audio.hpp \
    libs/SFML/include/SFML/Audio/AlResource.hpp \
    libs/SFML/include/SFML/Audio/Export.hpp \
    libs/SFML/include/SFML/Audio/InputSoundFile.hpp \
    libs/SFML/include/SFML/Audio/Listener.hpp \
    libs/SFML/include/SFML/Audio/Music.hpp \
    libs/SFML/include/SFML/Audio/OutputSoundFile.hpp \
    libs/SFML/include/SFML/Audio/Sound.hpp \
    libs/SFML/include/SFML/Audio/SoundBuffer.hpp \
    libs/SFML/include/SFML/Audio/SoundBufferRecorder.hpp \
    libs/SFML/include/SFML/Audio/SoundFileFactory.hpp \
    libs/SFML/include/SFML/Audio/SoundFileFactory.inl \
    libs/SFML/include/SFML/Audio/SoundFileReader.hpp \
    libs/SFML/include/SFML/Audio/SoundFileWriter.hpp \
    libs/SFML/include/SFML/Audio/SoundRecorder.hpp \
    libs/SFML/include/SFML/Audio/SoundSource.hpp \
    libs/SFML/include/SFML/Audio/SoundStream.hpp \
    libs/SFML/include/SFML/Config.hpp \
    libs/SFML/include/SFML/GpuPreference.hpp \
    libs/SFML/include/SFML/Graphics.hpp \
    libs/SFML/include/SFML/Graphics/BlendMode.hpp \
    libs/SFML/include/SFML/Graphics/CircleShape.hpp \
    libs/SFML/include/SFML/Graphics/Color.hpp \
    libs/SFML/include/SFML/Graphics/ConvexShape.hpp \
    libs/SFML/include/SFML/Graphics/Drawable.hpp \
    libs/SFML/include/SFML/Graphics/Export.hpp \
    libs/SFML/include/SFML/Graphics/Font.hpp \
    libs/SFML/include/SFML/Graphics/Glsl.hpp \
    libs/SFML/include/SFML/Graphics/Glsl.inl \
    libs/SFML/include/SFML/Graphics/Glyph.hpp \
    libs/SFML/include/SFML/Graphics/Image.hpp \
    libs/SFML/include/SFML/Graphics/PrimitiveType.hpp \
    libs/SFML/include/SFML/Graphics/Rect.hpp \
    libs/SFML/include/SFML/Graphics/Rect.inl \
    libs/SFML/include/SFML/Graphics/RectangleShape.hpp \
    libs/SFML/include/SFML/Graphics/RenderStates.hpp \
    libs/SFML/include/SFML/Graphics/RenderTarget.hpp \
    libs/SFML/include/SFML/Graphics/RenderTexture.hpp \
    libs/SFML/include/SFML/Graphics/RenderWindow.hpp \
    libs/SFML/include/SFML/Graphics/Shader.hpp \
    libs/SFML/include/SFML/Graphics/Shape.hpp \
    libs/SFML/include/SFML/Graphics/Sprite.hpp \
    libs/SFML/include/SFML/Graphics/Text.hpp \
    libs/SFML/include/SFML/Graphics/Texture.hpp \
    libs/SFML/include/SFML/Graphics/Transform.hpp \
    libs/SFML/include/SFML/Graphics/Transformable.hpp \
    libs/SFML/include/SFML/Graphics/Vertex.hpp \
    libs/SFML/include/SFML/Graphics/VertexArray.hpp \
    libs/SFML/include/SFML/Graphics/VertexBuffer.hpp \
    libs/SFML/include/SFML/Graphics/View.hpp \
    libs/SFML/include/SFML/Main.hpp \
    libs/SFML/include/SFML/Network.hpp \
    libs/SFML/include/SFML/Network/Export.hpp \
    libs/SFML/include/SFML/Network/Ftp.hpp \
    libs/SFML/include/SFML/Network/Http.hpp \
    libs/SFML/include/SFML/Network/IpAddress.hpp \
    libs/SFML/include/SFML/Network/Packet.hpp \
    libs/SFML/include/SFML/Network/Socket.hpp \
    libs/SFML/include/SFML/Network/SocketHandle.hpp \
    libs/SFML/include/SFML/Network/SocketSelector.hpp \
    libs/SFML/include/SFML/Network/TcpListener.hpp \
    libs/SFML/include/SFML/Network/TcpSocket.hpp \
    libs/SFML/include/SFML/Network/UdpSocket.hpp \
    libs/SFML/include/SFML/OpenGL.hpp \
    libs/SFML/include/SFML/System.hpp \
    libs/SFML/include/SFML/System/Clock.hpp \
    libs/SFML/include/SFML/System/Err.hpp \
    libs/SFML/include/SFML/System/Export.hpp \
    libs/SFML/include/SFML/System/FileInputStream.hpp \
    libs/SFML/include/SFML/System/InputStream.hpp \
    libs/SFML/include/SFML/System/Lock.hpp \
    libs/SFML/include/SFML/System/MemoryInputStream.hpp \
    libs/SFML/include/SFML/System/Mutex.hpp \
    libs/SFML/include/SFML/System/NativeActivity.hpp \
    libs/SFML/include/SFML/System/NonCopyable.hpp \
    libs/SFML/include/SFML/System/Sleep.hpp \
    libs/SFML/include/SFML/System/String.hpp \
    libs/SFML/include/SFML/System/String.inl \
    libs/SFML/include/SFML/System/Thread.hpp \
    libs/SFML/include/SFML/System/Thread.inl \
    libs/SFML/include/SFML/System/ThreadLocal.hpp \
    libs/SFML/include/SFML/System/ThreadLocalPtr.hpp \
    libs/SFML/include/SFML/System/ThreadLocalPtr.inl \
    libs/SFML/include/SFML/System/Time.hpp \
    libs/SFML/include/SFML/System/Utf.hpp \
    libs/SFML/include/SFML/System/Utf.inl \
    libs/SFML/include/SFML/System/Vector2.hpp \
    libs/SFML/include/SFML/System/Vector2.inl \
    libs/SFML/include/SFML/System/Vector3.hpp \
    libs/SFML/include/SFML/System/Vector3.inl \
    libs/SFML/include/SFML/Window.hpp \
    libs/SFML/include/SFML/Window/Clipboard.hpp \
    libs/SFML/include/SFML/Window/Context.hpp \
    libs/SFML/include/SFML/Window/ContextSettings.hpp \
    libs/SFML/include/SFML/Window/Cursor.hpp \
    libs/SFML/include/SFML/Window/Event.hpp \
    libs/SFML/include/SFML/Window/Export.hpp \
    libs/SFML/include/SFML/Window/GlResource.hpp \
    libs/SFML/include/SFML/Window/Joystick.hpp \
    libs/SFML/include/SFML/Window/Keyboard.hpp \
    libs/SFML/include/SFML/Window/Mouse.hpp \
    libs/SFML/include/SFML/Window/Sensor.hpp \
    libs/SFML/include/SFML/Window/Touch.hpp \
    libs/SFML/include/SFML/Window/VideoMode.hpp \
    libs/SFML/include/SFML/Window/Window.hpp \
    libs/SFML/include/SFML/Window/WindowHandle.hpp \
    libs/SFML/include/SFML/Window/WindowStyle.hpp \
    libs/TinyPNGOut/TinyPngOut.hpp \
    qrcode.h \
    vcard.h

DISTFILES += \
    libs/SFML/bin/openal32.dll \
    libs/SFML/bin/sfml-audio-2.dll \
    libs/SFML/bin/sfml-audio-d-2.dll \
    libs/SFML/bin/sfml-graphics-2.dll \
    libs/SFML/bin/sfml-graphics-d-2.dll \
    libs/SFML/bin/sfml-network-2.dll \
    libs/SFML/bin/sfml-network-d-2.dll \
    libs/SFML/bin/sfml-system-2.dll \
    libs/SFML/bin/sfml-system-d-2.dll \
    libs/SFML/bin/sfml-window-2.dll \
    libs/SFML/bin/sfml-window-d-2.dll \
    libs/SFML/lib/cmake/SFML/SFMLConfig.cmake \
    libs/SFML/lib/cmake/SFML/SFMLConfigDependencies.cmake \
    libs/SFML/lib/cmake/SFML/SFMLConfigVersion.cmake \
    libs/SFML/lib/cmake/SFML/SFMLSharedTargets-debug.cmake \
    libs/SFML/lib/cmake/SFML/SFMLSharedTargets-release.cmake \
    libs/SFML/lib/cmake/SFML/SFMLSharedTargets.cmake \
    libs/SFML/lib/cmake/SFML/SFMLStaticTargets-debug.cmake \
    libs/SFML/lib/cmake/SFML/SFMLStaticTargets-release.cmake \
    libs/SFML/lib/cmake/SFML/SFMLStaticTargets.cmake \
    libs/SFML/lib/libFLAC.a \
    libs/SFML/lib/libfreetype.a \
    libs/SFML/lib/libogg.a \
    libs/SFML/lib/libopenal32.a \
    libs/SFML/lib/libsfml-audio-d.a \
    libs/SFML/lib/libsfml-audio-s-d.a \
    libs/SFML/lib/libsfml-audio-s.a \
    libs/SFML/lib/libsfml-audio.a \
    libs/SFML/lib/libsfml-graphics-d.a \
    libs/SFML/lib/libsfml-graphics-s-d.a \
    libs/SFML/lib/libsfml-graphics-s.a \
    libs/SFML/lib/libsfml-graphics.a \
    libs/SFML/lib/libsfml-main-d.a \
    libs/SFML/lib/libsfml-main.a \
    libs/SFML/lib/libsfml-network-d.a \
    libs/SFML/lib/libsfml-network-s-d.a \
    libs/SFML/lib/libsfml-network-s.a \
    libs/SFML/lib/libsfml-network.a \
    libs/SFML/lib/libsfml-system-d.a \
    libs/SFML/lib/libsfml-system-s-d.a \
    libs/SFML/lib/libsfml-system-s.a \
    libs/SFML/lib/libsfml-system.a \
    libs/SFML/lib/libsfml-window-d.a \
    libs/SFML/lib/libsfml-window-s-d.a \
    libs/SFML/lib/libsfml-window-s.a \
    libs/SFML/lib/libsfml-window.a \
    libs/SFML/lib/libvorbis.a \
    libs/SFML/lib/libvorbisenc.a \
    libs/SFML/lib/libvorbisfile.a
